### ISSUE TITLE
Make combatible with eslint version 8?

### ISSUE THREAD

**Issue by owre** [chdsbd/eslint-plugin-better-dates#3]
Is there any plans to upgrade eslint version to 8?

Including this plugin when running version 8 produces the following error:

`TypeError: Failed to load plugin 'better-dates' declared in '.eslintrc.js': Class extends value undefined is not a constructor or null`

**Comment by chdsbd** [comment]
I probably won’t upgrade this repo to support Eslint 8 unless I need to for one of my projects, but I’d welcome any PR to make the change

**Comment by owre** [comment]
@chdsbd Thanks man, I'll see what I can do
